#!/usr/bin/env bash
set -uo pipefail;

####################################
# Ensure we can execute standalone #
####################################

function early_death() {
  echo "[FATAL] ${0}: ${1}" >&2;
  exit 1;
};

if [ -z "${ISTIOCTLENV_ROOT:-""}" ]; then
  # http://stackoverflow.com/questions/1055671/how-can-i-get-the-behavior-of-gnus-readlink-f-on-a-mac
  readlink_f() {
    local target_file="${1}";
    local file_name;

    while [ "${target_file}" != "" ]; do
      cd "$(dirname ${target_file})" || early_death "Failed to 'cd \$(dirname ${target_file})' while trying to determine ISTIOCTLENV_ROOT";
      file_name="$(basename "${target_file}")" || early_death "Failed to 'basename \"${target_file}\"' while trying to determine ISTIOCTLENV_ROOT";
      target_file="$(readlink "${file_name}")";
    done;

    echo "$(pwd -P)/${file_name}";
  };

  ISTIOCTLENV_ROOT="$(cd "$(dirname "$(readlink_f "${0}")")/.." && pwd)";
  [ -n "${ISTIOCTLENV_ROOT}" ] || early_death "Failed to 'cd \"\$(dirname \"\$(readlink_f \"${0}\")\")/..\" && pwd' while trying to determine ISTIOCTLENV_ROOT";
else
  ISTIOCTLENV_ROOT="${ISTIOCTLENV_ROOT%/}";
fi;
export ISTIOCTLENV_ROOT;

if [ -n "${ISTIOCTLENV_HELPERS:-""}" ]; then
  log 'debug' 'ISTIOCTLENV_HELPERS is set, not sourcing helpers again';
else
  [ "${ISTIOCTLENV_DEBUG:-0}" -gt 0 ] && echo "[DEBUG] Sourcing helpers from ${ISTIOCTLENV_ROOT}/lib/helpers.sh";
  if source "${ISTIOCTLENV_ROOT}/lib/helpers.sh"; then
    log 'debug' 'Helpers sourced successfully';
  else
    early_death "Failed to source helpers from ${ISTIOCTLENV_ROOT}/lib/helpers.sh";
  fi;
fi;

# Ensure libexec and bin are in $PATH
for dir in libexec bin; do
  case ":${PATH}:" in
    *:${ISTIOCTLENV_ROOT}/${dir}:*) log 'debug' "\$PATH already contains '${ISTIOCTLENV_ROOT}/${dir}', not adding it again";;
    *) 
      log 'debug' "\$PATH does not contain '${ISTIOCTLENV_ROOT}/${dir}', prepending and exporting it now";
      export PATH="${ISTIOCTLENV_ROOT}/${dir}:${PATH}";
      ;;
  esac;
done;

#####################
# Begin Script Body #
#####################

[ "${#}" -gt 1 ] && log 'error' 'usage: istioctlenv use [<version>]';

[ -d "${ISTIOCTLENV_ROOT}/versions" ] \
  || log 'error' 'No versions of istioctl installed. Please install one with: istioctlenv install';

declare requested="${1:-""}";

log debug "Resolving version with: istioctlenv-resolve-version ${requested}";
declare resolved="$(istioctlenv-resolve-version ${requested})";

declare version="${resolved%%\:*}";
declare regex="${resolved##*\:}";

log 'debug' "Searching ${ISTIOCTLENV_ROOT}/versions for latest version matching ${regex}";
declare version="$(\find "${ISTIOCTLENV_ROOT}/versions" -maxdepth 1 -type d -exec basename {} \; \
  | tail -n +2 \
  | sort -t'.' -k 1nr,1 -k 2nr,2 -k 3nr,3 \
  | grep -e "${regex}" \
  | head -n 1
)";

[ -n "${version}" ] \
  && log 'debug' "Found version: ${version}" \
  || log 'error' "No installed versions of istioctl matched '${1}'";

target_path="${ISTIOCTLENV_ROOT}/versions/${version}/bin";
[ -f "${target_path}/istioctl" ] \
  || log 'error' "Version directory for ${version} is present, but the istioctl binary is not! Manual intervention required.";
[ -x "${target_path}/istioctl" ] \
  || log 'error' "Version directory for ${version} is present, but the istioctl binary is not executable! Manual intervention required.";

log 'info' "Switching default version to v${version}";
version_file="${ISTIOCTLENV_ROOT}/version";
log 'debug' "Writing \"${version}\" to \"${version_file}\"";
echo "${version}" > "${version_file}" \
  || log 'error' "Switch to v${version} failed";

if [ "${version_file}" != "$(istioctlenv-version-file)" ]; then
  log 'warn' "Default version file overridden by $(istioctlenv-version-file), changing the default version has no effect";
fi;

istioctl version --short --remote=false 1>/dev/null \
  || log 'error' "'istioctl version' failed. Something is seriously wrong";
log 'info' "Switching completed";
