#!/usr/bin/env bash
# Summary: Show the currently-selected istioctl version

set -uo pipefail;

####################################
# Ensure we can execute standalone #
####################################

function early_death() {
  echo "[FATAL] ${0}: ${1}" >&2;
  exit 1;
};

if [ -z "${ISTIOCTLENV_ROOT:-""}" ]; then
  # http://stackoverflow.com/questions/1055671/how-can-i-get-the-behavior-of-gnus-readlink-f-on-a-mac
  readlink_f() {
    local target_file="${1}";
    local file_name;

    while [ "${target_file}" != "" ]; do
      cd "$(dirname ${target_file})" || early_death "Failed to 'cd \$(dirname ${target_file})' while trying to determine ISTIOCTLENV_ROOT";
      file_name="$(basename "${target_file}")" || early_death "Failed to 'basename \"${target_file}\"' while trying to determine ISTIOCTLENV_ROOT";
      target_file="$(readlink "${file_name}")";
    done;

    echo "$(pwd -P)/${file_name}";
  };

  ISTIOCTLENV_ROOT="$(cd "$(dirname "$(readlink_f "${0}")")/.." && pwd)";
  [ -n "${ISTIOCTLENV_ROOT}" ] || early_death "Failed to 'cd \"\$(dirname \"\$(readlink_f \"${0}\")\")/..\" && pwd' while trying to determine ISTIOCTLENV_ROOT";
else
  ISTIOCTLENV_ROOT="${ISTIOCTLENV_ROOT%/}";
fi;
export ISTIOCTLENV_ROOT;

if [ -n "${ISTIOCTLENV_HELPERS:-""}" ]; then
  log 'debug' 'ISTIOCTLENV_HELPERS is set, not sourcing helpers again';
else
  [ "${ISTIOCTLENV_DEBUG:-0}" -gt 0 ] && echo "[DEBUG] Sourcing helpers from ${ISTIOCTLENV_ROOT}/lib/helpers.sh";
  if source "${ISTIOCTLENV_ROOT}/lib/helpers.sh"; then
    log 'debug' 'Helpers sourced successfully';
  else
    early_death "Failed to source helpers from ${ISTIOCTLENV_ROOT}/lib/helpers.sh";
  fi;
fi;

# Ensure libexec and bin are in $PATH
for dir in libexec bin; do
  case ":${PATH}:" in
    *:${ISTIOCTLENV_ROOT}/${dir}:*) log 'debug' "\$PATH already contains '${ISTIOCTLENV_ROOT}/${dir}', not adding it again";;
    *) 
      log 'debug' "\$PATH does not contain '${ISTIOCTLENV_ROOT}/${dir}', prepending and exporting it now";
      export PATH="${ISTIOCTLENV_ROOT}/${dir}:${PATH}";
      ;;
  esac;
done;

#####################
# Begin Script Body #
#####################

[ -d "${ISTIOCTLENV_ROOT}/versions" ] \
  || log 'error' 'No versions of istioctl installed. Please install one with: istioctlenv install';

ISTIOCTLENV_VERSION_FILE="$(istioctlenv-version-file)" \
  && log 'debug' "ISTIOCTLENV_VERSION_FILE retrieved from istioctlenv-version-file: ${ISTIOCTLENV_VERSION_FILE}" \
  || log 'error' 'Failed to retrieve ISTIOCTLENV_VERSION_FILE from istioctlenv-version-file';

ISTIOCTLENV_VERSION="$(cat "${ISTIOCTLENV_VERSION_FILE}" || true)" \
  && log 'debug' "ISTIOCTLENV_VERSION specified in ISTIOCTLENV_VERSION_FILE: ${ISTIOCTLENV_VERSION}";

if [[ "${ISTIOCTLENV_VERSION}" =~ ^latest.*$ ]]; then
  log 'debug' "ISTIOCTLENV_VERSION uses 'latest' keyword: ${ISTIOCTLENV_VERSION}";

  if [[ "${ISTIOCTLENV_VERSION}" =~ ^latest\:.*$ ]]; then
    regex="${ISTIOCTLENV_VERSION##*\:}";
    log 'debug' "'latest' keyword uses regex: ${regex}";
  else
    regex='.*'; # Just saves a seperate command below without the grep
    log 'debug' "'latest' keyword does not use regex";
  fi;

  version="$(\find "${ISTIOCTLENV_ROOT}/versions" -type d -exec basename {} \; \
    | tail -n +2 \
    | sort -t'.' -k 1nr,1 -k 2nr,2 -k 3nr,3 \
    | grep -e "${regex}" \
    | head -n 1)";

  if [ -n "${version}" ]; then
    log 'debug' "Version selected: ${version}";
    ISTIOCTLENV_VERSION="${version}"
  else
    log 'error' "No installed versions of istioctl matched '${ISTIOCTLENV_VERSION}'";
  fi;

else
  log 'debug' 'ISTIOCTLENV_VERSION does not use "latest" keyword';
fi;

[ -z "${ISTIOCTLENV_VERSION}" ] \
  && log 'error' "Version could not be resolved (set by ${ISTIOCTLENV_VERSION_FILE} or istioctlenv use <version>)";

if [ ! -d "${ISTIOCTLENV_ROOT}/versions/${ISTIOCTLENV_VERSION}" ]; then
  log 'debug' "version '${ISTIOCTLENV_VERSION}' is not installed (set by ${ISTIOCTLENV_VERSION_FILE})";
fi;

echo "${ISTIOCTLENV_VERSION}";

