#!/usr/bin/env bash

set -uo pipefail;

####################################
# Ensure we can execute standalone #
####################################

function early_death() {
  echo "[FATAL] ${0}: ${1}" >&2;
  exit 1;
};

if [ -z "${ISTIOCTLENV_ROOT:-""}" ]; then
  # http://stackoverflow.com/questions/1055671/how-can-i-get-the-behavior-of-gnus-readlink-f-on-a-mac
  readlink_f() {
    local target_file="${1}";
    local file_name;

    while [ "${target_file}" != "" ]; do
      cd "$(dirname ${target_file})" || early_death "Failed to 'cd \$(dirname ${target_file})' while trying to determine ISTIOCTLENV_ROOT";
      file_name="$(basename "${target_file}")" || early_death "Failed to 'basename \"${target_file}\"' while trying to determine ISTIOCTLENV_ROOT";
      target_file="$(readlink "${file_name}")";
    done;

    echo "$(pwd -P)/${file_name}";
  };

  ISTIOCTLENV_ROOT="$(cd "$(dirname "$(readlink_f "${0}")")/.." && pwd)";
  [ -n "${ISTIOCTLENV_ROOT}" ] || early_death "Failed to 'cd \"\$(dirname \"\$(readlink_f \"${0}\")\")/..\" && pwd' while trying to determine ISTIOCTLENV_ROOT";
else
  ISTIOCTLENV_ROOT="${ISTIOCTLENV_ROOT%/}";
fi;
export ISTIOCTLENV_ROOT;

if [ -n "${ISTIOCTLENV_HELPERS:-""}" ]; then
  log 'debug' 'ISTIOCTLENV_HELPERS is set, not sourcing helpers again';
else
  [ "${ISTIOCTLENV_DEBUG:-0}" -gt 0 ] && echo "[DEBUG] Sourcing helpers from ${ISTIOCTLENV_ROOT}/lib/helpers.sh";
  if source "${ISTIOCTLENV_ROOT}/lib/helpers.sh"; then
    log 'debug' 'Helpers sourced successfully';
  else
    early_death "Failed to source helpers from ${ISTIOCTLENV_ROOT}/lib/helpers.sh";
  fi;
fi;

# Ensure libexec and bin are in $PATH
for dir in libexec bin; do
  case ":${PATH}:" in
    *:${ISTIOCTLENV_ROOT}/${dir}:*) log 'debug' "\$PATH already contains '${ISTIOCTLENV_ROOT}/${dir}', not adding it again";;
    *) 
      log 'debug' "\$PATH does not contain '${ISTIOCTLENV_ROOT}/${dir}', prepending and exporting it now";
      export PATH="${ISTIOCTLENV_ROOT}/${dir}:${PATH}";
      ;;
  esac;
done;

#####################
# Begin Script Body #
#####################

if [ "${#}" -ne 0 ];then
  echo "usage: istioctlenv list-remote" 1>&2
  exit 1;
fi

ISTIOCTLENV_REMOTE="${ISTIOCTLENV_REMOTE:-https://api.github.com/repos/istio/istio/releases}"
log 'debug' "ISTIOCTLENV_REMOTE: ${ISTIOCTLENV_REMOTE}";

declare remote_versions;
remote_versions="$(curlw -sSf "${ISTIOCTLENV_REMOTE}")" \
  || log 'error' "Failed to download remote versions from ${ISTIOCTLENV_REMOTE}";

grep -o -E 'releases/[0-9]+\.[0-9]+\.[0-9]+/' <<<"${remote_versions}" | sort -r | uniq | awk -F'/' '{ print $2}';
